### ISSUE TITLE
Github Pages Build Failure

### ISSUE THREAD

**Issue by orion-miller** [zerostaticthemes/jekyll-serif-theme#107]
Hi all,

I've forked this repo and tried building with Github Pages. The only change I've made to the source code is updating the base-url according to my repo name per the README. I'm getting the following errors when running the build:

![image](https://github.com/user-attachments/assets/0c5b656b-ac03-4868-9998-a80161e5b8fb)

Any feedback on what dependency Github Pages is not able to support? Do I need to make a workflow through Github Actions as suggested?

Thanks,
Orion

**Comment by dhammo2** [comment]
@orion-miller Please see my instructions here to resolve this issue. I have created a merge request with the fix: https://github.com/zerostaticthemes/jekyll-serif-theme/pull/111/commits/0abb748c4858dbe92bdea76b9ff81ab7a20c86e1

**Comment by amirsadighpourdds** [comment]
> @orion-miller Please see my instructions here to resolve this issue. I have created a merge request with the fix: [0abb748](https://github.com/zerostaticthemes/jekyll-serif-theme/commit/0abb748c4858dbe92bdea76b9ff81ab7a20c86e1)

I followed the instructions in the new commit and it worked! Thanks a lot. Any idea why deploying from a branch doesn't work with jekyll? I thought it was automatically supported for some reason.

**Comment by orion-miller** [comment]
Ok I see that, thanks! Closing this issue.
