### ISSUE TITLE
General project comments

### ISSUE THREAD

**Issue by antgel** [zerostaticthemes/jekyll-serif-theme#16]
Hi, firstly thanks for a great theme. Absolutely love working with it.

I'm wondering - it seems pretty popular with 146 stars and 178 forks - perhaps it would be worth considering some or all of the following:

* It would be nice if git commit messages were a bit more explanatory - it's not that easy from `git log` to follow what has been done, one always needs to go into the commits.
* In massive commits like 570b0b4f5c6a336a5f5e6bd211f18176b2bea7ae, it would be great to know what the thinking was behind the changes. My site is simple, yet it was pretty challenging to rebase on this commit when I wanted to pull in the latest changes. Perhaps a `CHANGELOG.md`?
* Perhaps using Pull Requests would provide part of a framework for the above?

Again, no complaints, just food for thought. :)

**Comment by JugglerX** [comment]
@antgel thank you for your feedback.

Honestly I had not given much thought to how my updates would effect downstream forks.  Building and maintaining the themes themselves is a lot of work already. 

Your suggestion is very reasonable, and constructive. And it's nice to get some validation that there are people who continue to update their forks over time.

I will attempt to make the commits clearer and more manageable in the future. But It's unlikely I will introduce a more complex process for maintaining the theme ie PR, rebasing or some kind of semver / changelog methodology. It's simply a matter of lack of time for me. 

I did create a basic changelog for this major release - https://github.com/zerostaticthemes/jekyll-serif-theme/releases/tag/v1.1 but I know it's not great. 

Let me think on it some more, perhaps there is some tooling I can integrate into my open source themes that will automate this to some degree.
