### ISSUE TITLE
Team overview page does not link to individual pages

### ISSUE THREAD

**Issue by smacz42** [zerostaticthemes/jekyll-serif-theme#24]
Hey all,

I am really happy about being able to use this theme, it's really clean and fun to work with!

I found that in the teams.html, there is no link to the individual pages from anywhere on the team member's pages. This is especially confusing since the promoted teams have their bio's truncated. I was able to verify that the pages were in fact rendered and exist on the site, I just don't think that there is any link that actually points to them.

I'm not sure if that was taken into consideration, but I thought it was worth bringing up as it was really the only part of the site that has been non-intuitive thus far. Keep up the good work!

**Comment by JugglerX** [comment]
@smacz42 Yes this is by design. I'd be happy for teams.html to link to the individual pages as the default. If you have made this change already could you do a PR?
