### ISSUE TITLE
What is intro_image_absolute used for?

### ISSUE THREAD

**Issue by antgel** [zerostaticthemes/jekyll-serif-theme#27]
As per subject really - I saw the images moving around when I added or removed text on the left of the `intro` row, then I noticed the hard-coded widths. After digging into the `_sass/components/_intro-image.scss`, I saw that this was done on purpose.

Setting `intro_image_absolute: false` worked well for me, but I'd be interested to know the use case for `true`.

**Comment by JugglerX** [comment]
@antgel setting this to true will make the image use css absolute positioning so that it "breaks out" of the grid. It's a visual effect that looks good with some illustrations, but often looks crap with regular image.

I agree the naming of this property could be better.
