### ISSUE TITLE
Pointing.svg is not aligned correctly on landing page.

### ISSUE THREAD

**Issue by Microunivercity** [zerostaticthemes/jekyll-serif-theme#28]
![image](https://user-images.githubusercontent.com/68999246/102693247-574d7900-423f-11eb-9f47-f583f2555aab.png)

The **pointing.svg** is not aligned correctly. *[check the red box]* 

I am new to Jekyll so not sure where is the style sheet so I could fix it.

Can someone please fix and let me know so I can fix in my current project too as I have customized everything except this.

Trillion thanks in advance.

__BR/MUnivercity__

**Comment by jmrchelani** [comment]
Hello,
In the index.md, change the intro_image_absolute to false and it will be okay; it fixed mine like this.
I dont know how and why - but it did. so yea!

**Comment by JugglerX** [comment]
@Microunivercity This is by design. The illustration is intended to "break out" of the grid.

Clearly this effect isnt for everyone. I think I need to name the `intro_image_absolute` property better. Maybe `intro_image_contained`?
