### ISSUE TITLE
Images similar to the one already inserted

### ISSUE THREAD

**Issue by EdoardoVimercati** [zerostaticthemes/jekyll-serif-theme#38]
Hello,
I was wondering if there is a repository of svg images in the style you already put in the illustration folder.
It would be amazing since of course those two images don't fit every use case.

Thanks a lot for the amazing work

**Comment by y377** [comment]
yes,I replaced both of them myself
[demo](https://www.ruomi.net)

**Comment by JugglerX** [comment]
@EdoardoVimercati @y377 Thanks, I'm glad you like the theme! 

@EdoardoVimercati from memory the illustrations I used in this theme come from https://icons8.com/illustrations - Amazing stuff.

@y377 If you like my work and would like to support me then check out my premium themes https:/www.zerostatic.io - Unfortunately I'm not currently available to do paid customisation.
