### ISSUE TITLE
home.html: Missing quotation marks in alt attribute in intro image

### ISSUE THREAD

**Issue by Balaiseee** [zerostaticthemes/jekyll-serif-theme#45]
In `home.html` :

`<img alt={{ page.title }} class="intro-image{% if page.intro_image_absolute %} intro-image-absolute{% endif %}{% if page.intro_image_hide_on_mobile %} intro-image-hide-mobile{% endif %}" src="{{ page.intro_image | relURL }}" />`

Once the site is generated :

`<img alt="Jekyll" serif="" theme="" class="intro-image intro-image-absolute intro-image-hide-mobile" src="images/illustrations/pointing.svg">`

Solved in #44 with this solution :

`<img alt="{{ page.title }}" class="intro-image{% if page.intro_image_absolute %} intro-image-absolute{% endif %}{% if page.intro_image_hide_on_mobile %} intro-image-hide-mobile{% endif %}" src="{{ page.intro_image | relURL }}" />`

**Comment by Emkann** [comment]
> In `home.html` :
> 
> 
> 
> `<img alt={{ page.title }} class="intro-image{% if page.intro_image_absolute %} intro-image-absolute{% endif %}{% if page.intro_image_hide_on_mobile %} intro-image-hide-mobile{% endif %}" src="{{ page.intro_image | relURL }}" />`
> 
> 
> 
> Once the site is generated :
> 
> 
> 
> `<img alt="Jekyll" serif="" theme="" class="intro-image intro-image-absolute intro-image-hide-mobile" src="images/illustrations/pointing.svg">`
> 
> 
> 
> Solved in #44 with this solution :
> 
> 
> 
> `<img alt="{{ page.title }}" class="intro-image{% if page.intro_image_absolute %} intro-image-absolute{% endif %}{% if page.intro_image_hide_on_mobile %} intro-image-hide-mobile{% endif %}" src="{{ page.intro_image | relURL }}" />`
