### ISSUE TITLE
Changing Serif Theme Color and webpage tab icon

### ISSUE THREAD

**Issue by Firesinger13** [zerostaticthemes/jekyll-serif-theme#46]
Hello, I forked your Serif Jekyll theme and I am struggling with how to change the primary colors of the theme. For instance, the repository I forked from you has Red as the primary color, I see the demo image however is Blue, I’d like it to be a shade of green. **EDIT: I found the answer to this question in assets -> css -> style.scss**.

I found the webpage logo, but can’t find the place where the ‘favicon-32x32.svg’ is referenced so I can change the icon that appears on the webpage tab. But I suppose I could swap a different file with the same name and it might work.

**Comment by JugglerX** [comment]
The favicon is set in the <head> of the `_layouts/default.html` - 

```
  <link rel="icon" type="image/png" href="{{ '/images/favicon-32x32.svg' | relative_url }}">
```

So you an edit this line and use a different path to your own favicon file. 

Or you can also just overwrite the `favicon-32x32.svg` in the images folder
