### ISSUE TITLE
Unable to build the site due to SCSS error.

### ISSUE THREAD

**Issue by ilijalazarevic** [zerostaticthemes/jekyll-serif-theme#78]
Hi,

I'm trying to build your theme and I'm having issue with `bundle exec jekyll build`.

Here are the gems versions:
```
Using public_suffix 5.0.1
Using addressable 2.8.4
Using bundler 2.3.25
Using colorator 1.1.0
Using concurrent-ruby 1.2.2
Using eventmachine 1.2.7
Using http_parser.rb 0.8.0
Using em-websocket 0.5.3
Using ffi 1.15.5
Using forwardable-extended 2.6.0
Using google-protobuf 3.23.3 (x86_64-linux)
Using i18n 1.14.1
Using sass-embedded 1.63.6 (x86_64-linux-musl)
Using jekyll-sass-converter 3.0.0
Using rb-fsevent 0.11.2
Using rb-inotify 0.10.1
Using listen 3.8.0
Using jekyll-watch 2.2.1
Using rexml 3.2.5
Using kramdown 2.4.0
Using kramdown-parser-gfm 1.1.0
Using liquid 4.0.4
Using mercenary 0.4.0
Using pathutil 0.16.2
Using rouge 4.1.2
Using safe_yaml 1.0.5
Using unicode-display_width 2.4.2
Using terminal-table 3.0.2
Using webrick 1.8.1
Using jekyll 4.3.2
Using jekyll-environment-variables 1.0.1
```

and here is the error that I get:

```
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
                    Broken pipe
                    ------------------------------------------------
      Jekyll 4.3.2   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/usr/gem/gems/sass-embedded-1.63.6-x86_64-linux-musl/lib/sass/embedded/varint.rb:35:in `write': Broken pipe (Errno::EPIPE)
...
...
```

This goes further through the stack trace, I'm not including it for the brevity.

Can you please help? Thanks!

**Comment by gonzoknows** [comment]
Getting a similar issue except mine deploys 

`Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2) or calc($spacer / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
302 │ $headings-margin-bottom:      $spacer / 2 !default;
    │                               ^^^^^^^^^^^
    ╵
    /home/thinkpad/jekyll-serif-theme-master/_sass/bootstrap/_variables.scss 302:31  @import
    bootstrap/bootstrap-reboot.scss 10:9                                             @import
    /home/thinkpad/jekyll-serif-theme-master/assets/css/style.scss 28:9              root stylesheet
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($input-padding-y, 2) or calc($input-padding-y / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
498 │ $input-height-inner-quarter:            add($input-line-height * .25em, $input-padding-y / 2) !default;
    │                                                                         ^^^^^^^^^^^^^^^^^^^^
    ╵
    /home/thinkpad/jekyll-serif-theme-master/_sass/bootstrap/_variables.scss 498:73  @import
    bootstrap/bootstrap-reboot.scss 10:9                                             @import
    /home/thinkpad/jekyll-serif-theme-master/assets/css/style.scss 28:9              root stylesheet
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($custom-control-indicator-size, 2) or calc($custom-control-indicator-size / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
568 │ $custom-switch-indicator-border-radius:         $custom-control-indicator-size / 2 !default;
    │                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    /home/thinkpad/jekyll-serif-theme-master/_sass/bootstrap/_variables.scss 568:49  @import
    bootstrap/bootstrap-reboot.scss 10:9                                             @import
    /home/thinkpad/jekyll-serif-theme-master/assets/css/style.scss 28:9              root stylesheet
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2) or calc($spacer / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
713 │ $nav-divider-margin-y:              $spacer / 2 !default;
    │                                     ^^^^^^^^^^^
    ╵
    /home/thinkpad/jekyll-serif-theme-master/_sass/bootstrap/_variables.scss 713:37  @import
    bootstrap/bootstrap-reboot.scss 10:9                                             @import
    /home/thinkpad/jekyll-serif-theme-master/assets/css/style.scss 28:9              root stylesheet
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2) or calc($spacer / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
718 │ $navbar-padding-y:                  $spacer / 2 !default;
    │                                     ^^^^^^^^^^^
    ╵
    /home/thinkpad/jekyll-serif-theme-master/_sass/bootstrap/_variables.scss 718:37  @import
    bootstrap/bootstrap-reboot.scss 10:9                                             @import
    /home/thinkpad/jekyll-serif-theme-master/assets/css/style.scss 28:9              root stylesheet
Warning: 22 repetitive deprecation warnings omitted.
Run in verbose mode to see all warnings.
`

**Comment by fabriciosb** [comment]
I had those warnings as well, but the site was built.

Yet, one can solve it runing:
```
$ npm install -g sass-migrator
$ sass-migrator division ./_sass/*.scss
```

This will update the .scss files and you can build without any warnings.

**Comment by JugglerX** [comment]
This issue will be fixed by PR https://github.com/zerostaticthemes/jekyll-serif-theme/pull/82 and we've also upgraded to Bootstrap 5.3.2

**Comment by QuillPusher** [comment]
Still facing this issue. tried the "npm install..." steps above, got a "Nothing to Migrate" notice. Others are facing similar issues, posted in this open issue: [91](https://github.com/zerostaticthemes/jekyll-serif-theme/issues/91)

**Comment by JugglerX** [comment]
this theme doesnt use npm, so npm install wont do anything.

**Comment by missingfaktor** [comment]
I'm trying to use this theme right now. I'm on `master`, [latest commit](a323305ac59c537850ad35334df7a10124d4ca80), and I'm running into the same error.
